function windowSize(){if($(window).width()>=960){windowHeight=Math.round(window.innerHeight?window.innerHeight:$(window).height());$('div.containers').height(windowHeight);$('section.no-table').each(function(){middleHeight=Math.round((windowHeight-$(this).height())/2);$(this).css("paddingTop",middleHeight);});$('section.table').height(windowHeight-90);$('section.table table').height(windowHeight-90);$('td.img').each(function(){if($(this).width()>$(this).children('img').width()||$(this).children('img').height()>windowHeight-90){$(this).children('img').css("maxHeight",windowHeight-90);$(this).children('img').width('auto');}else{$(this).children('img').css("maxHeight",'none');$(this).children('img').width('100%');}});$('div.features-container nav').css('marginTop',Math.round(((windowHeight)/2)-($('div.features-container nav').height()/2)+45));}else{$('div.containers').height('auto');$('section.table').height('auto');$('section.table table').height('auto');$('section.no-table').css("paddingTop",190);}}
function windowScroll(parent,direction){if(direction=='prev'&&$("div."+parent+"-container").prev().hasClass('containers')){newPosition=$("div."+parent+"-container").prev().attr("name");}else if(direction=='next'&&$("div."+parent+"-container").next().hasClass('containers')){newPosition=$("div."+parent+"-container").next().attr("name");}else{return false;}
$('div.menu-container').attr("position",newPosition);$('html, body').animate({scrollTop:$("div."+newPosition+"-container").offset().top},1000);}
function mouseWheel(){$('html, body').unbind('mousewheel');if($(window).width()>=960){var doMouseWheel=true;$('html, body').bind('mousewheel',function(event,delta){if(!doMouseWheel)
return false;doMouseWheel=false;if(delta>0){windowScroll($('div.menu-container').attr("position"),"prev");}else{windowScroll($('div.menu-container').attr("position"),"next");}
setTimeout(turnWheelBackOn,500);});function turnWheelBackOn(){doMouseWheel=true;}
onkeydown=function(e){var touche=e.keyCode;var touche_lettre=String.fromCharCode(touche);if(touche==38||touche_lettre=="&"){windowScroll($('div.menu-container').attr("position"),"prev");return false;}else if(touche==40||touche_lettre=="("){windowScroll($('div.menu-container').attr("position"),"next");return false;}}}}
jQuery(function($){window.scrollTo(0,0);windowSize();mouseWheel();$(window).scroll(function(){if($(window).width()>=960){if($(window).scrollTop()+$('div.containers').height()>$('div.containers').height()){$("span.visit-direction").hide();}else{$("span.visit-direction").show();}
$('div.containers').each(function(){var position=$(this).position();if(position.top+($(this).height()/2)>=$(window).scrollTop()){$("nav.shortcut-container a").removeClass('active');$("a."+$(this).attr("name")+"-shortcut").addClass('active');$('div.menu-container').attr("position",$(this).attr("name"));$("a.scroll-arrows.top").attr('title',$('nav.shortcut-container a.'+$(this).attr("name")+'-shortcut').prev().attr('title'));if($(this).attr("name")=="discover"){$("a.scroll-arrows.top").hide();}else{$("a.scroll-arrows.top").show();}
$("a.scroll-arrows.bottom").attr('title',$('nav.shortcut-container a.'+$(this).attr("name")+'-shortcut').next().attr('title'));if($(this).attr("name")=="ready-to-start"){$("a.scroll-arrows.bottom").hide();}else{$("a.scroll-arrows.bottom").show();}
return false;}});}});$('a.scroll-arrows.top').click(function(){windowScroll($('div.menu-container').attr("position"),"prev");return false;});$('a.scroll-arrows.bottom').click(function(){windowScroll($('div.menu-container').attr("position"),"next");return false;});$('nav.shortcut-container a').click(function(){$('html, body').animate({scrollTop:$("div."+$(this).attr("key")+"-container").offset().top},1000);return false;});$('div.features-container nav a').click(function(){link=$(this);$("div.features-container nav a").removeClass('active');link.addClass('active');$('div.features-container td.img2 img').stop();$('div.features-container td.img2 img').animate({marginLeft:-$('div.features-container td.img2 img').width()*3},500,function(){$("div.features-container td.text div").hide();$("div.features-container td.text div."+link.attr("key")).show();$('div.features-container td.img2 img').attr("src",'/img/img_'+link.attr("key")+'.png');$('div.features-container td.img2 img').animate({marginLeft:0},500);});return false;});$(window).resize(function(){if($(window).width()>=960){window.scrollTo(0,0);$("a.scroll-arrows.bottom").show();$("span.visit-direction").show();}else{$("a.scroll-arrows.bottom").hide();$("span.visit-direction").hide();}
windowSize();mouseWheel();});});